version: '3'
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5328:5328"
    environment:
      - FLASK_DEBUG=1
    networks:
      - my-network
    volumes:
      - bpl-data:/api/data

  react-app:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - my-network

networks:
  my-network:

volumes:
  bpl-data: