version: '3'
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5328:5328"
    environment:
      - FLASK_DEBUG=1
    networks:
      - app-network
    volumes:
      - bpl-data:/api/data

  react-app:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - app-network
      - ngrok-network

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    networks:
      - ngrok-network

networks:
  app-network:
  ngrok-network:

volumes:
  bpl-data: