version: '4'
# DEPLOYMENT - pulls images
services:
  flask-app:
    image: shelbyjm/bpl-app-flask-app:latest  # your Docker Hub image name

    ports:
      - "5328:5328"
    environment:
      - FLASK_DEBUG=0
    networks:
      - app-network
    volumes:
      - bpl-data-deploy:/api/data

  react-app:
    image: shelbyjm/bpl-app-react-app:latest  # your Docker Hub image name

    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - app-network

networks:
  app-network:

volumes:
  bpl-data: